### ISSUE TITLE
Get appropriate CSL bibliography format 

### ISSUE THREAD

**Issue by Pakillo** [ecoinfAEET/Reproducibilidad#1]
We need to get a CSL format for the journal (Ecosistemas) or alternatively find one from another journal that has the same format. Or else we will have to modify any, or ask the journal to provide it

**Comment by ajpelu** [comment]
I asked to Editorial board of the journal. I will inform you with their reply

**Comment by Pakillo** [comment]
Done: https://github.com/citation-style-language/styles/blob/master/ecosistemas.csl
