### ISSUE TITLE
Improve table formatting

### ISSUE THREAD

**Issue by Pakillo** [ecoinfAEET/Reproducibilidad#12]
> El formateo de las Tablas 1 and 2 debe ser mejorado. Cada tabla debe aportar su correspondiente encabezamiento explicativo.

Ideas?

**Comment by ajpelu** [comment]
@Pakillo, como las tablas son simples (1 sola columna) se me ocurren dos opciones: 
- En vez de que sean tablas, convertirlas a algo estilo box, o
- Incluir un nombre de columna, cambiando 
  colnames(tabla2) <- NULL 

Que os parece?

**Comment by Pakillo** [comment]
Gracias @ajpelu. Claro que son tablas un poco particulares. Podríamos intentar la segunda opción (no está claro que Ecosistemas incluya boxes). Pero no se me ocurre ningún nombre de columna 'inteligente'... (beneficio? criterio? nah)

**Comment by ajpelu** [comment]
Buenas de nuevo, 
se me ocurre que podemos ponerle el siguiente nombre de columna: 
- Tabla 1: Beneficios de la ciencia reproducible 
- Tabla 2: Consejos para aumentar la reproducibilidad 

Se que son algo redundantes con las captions de las tablas, pero no se me ocurre otra idea. 

Por otro lado, en `pander:pandoc.table(...)` utilizar `style='simple'` o `style='multiline'` puede ayudar a mejorar el formato. 

No se si servirá,
