### ISSUE TITLE
Cómo facilitar el aprendizaje de técnicas de reproducibilidad

### ISSUE THREAD

**Issue by Pakillo** [ecoinfAEET/Reproducibilidad#15]
El revisor B escribe:

> "En general, el manuscrito está muy bien escrito y fácil de seguir. Sin embargo, echo de menos una sección que mencionase los desafíos del aprendizaje. Normalmente, profesores universitarios tienen una demanda muy grande de servicios. [...] Uno de los grandes desafíos para los investigadores y profesores universitarios es encontrar tiempo para aprender una metodología nueva y compleja. Los autores podrían mencionar esta limitación en el texto." 
> 
> "Otra limitación es que lenguaje de programación, en general, no es incluida en los currículos de la mayoría de los cursos de ecología o cursos afines. Algunas Universidades/Departamentos imparten cursos “puntuales” para un publico muy específico. Este aprendizaje es fundamental para viabilizar una ciencia reproducible. Aunque los autores especifican que “La transición hacia la reproducibilidad puede hacerse gradualmente” (Línea 345), creo que los autores podrían desarrollar un poco más este tema. Los autores podrían reconocer esta limitación en el texto y proponer estrategias para la enseñanza de la programación en carreras de ecología/ambientales y carreras afines en el nivel superior. Por ejemplo, los profesores/instructores involucrados en este proceso deben tener en cuenta: el desconocimiento de la materia, carencia de disciplina de programación, desinterés, apatía por el lenguaje de programación o carencias de habilidades para programar."

No sé muy bien cómo enfocar esto en el ms, más allá de los comentarios que ya tenemos al inicio de la sección de 'Cómo hacer ciencia reproducible' y las Conclusiones. 

En mi opinión, una vez somos conscientes de la importancia de la reproducibilidad, el énfasis debe estar en la formación de los nuevos ecólogos (master, doctorado) en este tipo de técnicas. Mi experiencia con estudiantes de master y doctorado es que si se les introduce a este tipo de técnicas desde el principio las adoptan muy bien, sin ningún tipo de problema.

La situación de los profesores de universidad e investigadores establecidos es diferente en mi opinión. Al igual que muchos de ellos no hacen ningún análisis per se (sino que lo hacen sus doctorandos o postdocs), a muchos no les interesará o merecerá la pena invertir en aprender a hacer ciencia reproducible (pero sí estimular a sus estudiantes para que la aprendan y practiquen - en parte porque las revistas se lo van a pedir!). Para los investigadores establecidos deberá de ser una decisión personal, como la de aprender R, Bayesiano, genómica o lo que sea. Nuestro ms y colección de recursos son una puerta de entrada y ayuda una vez tomada esa decisión.

Qué os parece? Ideas? Puedo decir todo esto en la carta de respuesta, pero se os ocurren cambios concretos para el ms?

**Comment by SaraVarela** [comment]
Hola chicos,

a mi me parece que lo que está exponiendo este revisor es su caso personal. me da la impresión de que parece que le apetecería aprender pero que debe estar muy cargado de clases, etc. y se agobia... 

yo, si realmente es necesario, pondría una frase para decir que, evidentemente, como cualquier cosa nueva, requiere un tiempo de aprendizaje y un poco de interés (obvio...!), y que sería importante impartir cursos y talleres en las universidades y centros de investigación para que tanto los estudiantes como los profesores e investigadores tuviesen facilidades para aprender a programar e incorporar estas nuevas técnicas en su trabajo. (de todas formas mira que hay cursos en diferentes universidades desde hace años, y cursos en internet y de tó... casi casi lo más importante es que la persona tenga interés, porque facilidades ya hay...)

besotes!

**Comment by Pakillo** [comment]
Gracias Sara. Coincido plenamente contigo. Y Nacho piensa igual (acabo de hablar con él). Meteré alguna cosa en el ms, y luego explicamos todo esto en la cover letter

**Comment by ajpelu** [comment]
Hola chicos, 
estoy totalmente de acuerdo con lo que proponéis, creo que con una buena justificación en el cover letter basta. 

Gracias. 

Seguimos. 

-- 
Antonio Jesús Pérez-Luque
Laboratorio de Ecología 
Instituto Interuniversitario del Sistema Tierra de Andalucía 
Universidad de Granada - Junta de Andalucía
Avda. del Mediterráneo S/N. 18006. Granada. España
Tel: +34 958 249748 

http://ajperezluque.com 
twitter: https://twitter.com/ajpelu

Este mensaje se dirige exclusivamente a su destinatario y puede contener información privilegiada o confidencial. Si no es Ud. el destinatario indicado, queda notificado de que la utilización, divulgación o copia sin autorización está prohibida en virtud de la legislación vigente. Si ha recibido este mensaje por error, se ruega lo comunique inmediatamente por esta misma vía y proceda a su destrucción.
 
This message is intended exclusively for its addressee and may contain information that is CONFIDENTIAL and protected by professional privilege. If you are not the intended recipient you are hereby notified that any dissemination, copy or disclosure of this communication is strictly prohibited by law. If this message has been received in error, please immediately notify us via e-mail and delete it

En 10 de mayo de 2016 en 14:19:40, Francisco Rodriguez-Sanchez (notifications@github.com) escrito:

Gracias Sara. Coincido plenamente contigo. Y Nacho piensa igual (acabo de hablar con él). Meteré alguna cosa en el ms, y luego explicamos todo esto en la cover letter
