### ISSUE TITLE
Table format

### ISSUE THREAD

**Issue by ajpelu** [ecoinfAEET/Reproducibilidad#3]
@Pakillo, 
No consigo formatear bien las tablas con knitr::kable. 
He intentado también con [pander](http://rapporter.github.io/pander/#pander-an-r-pandoc-writer), pero nada
¿A ti te las genera bien?

**Comment by Pakillo** [comment]
Hay muchas formas de sacar tablas en rmarkdown (aunque nuestras tablas son un poco raras :). 

pandoc.table va bien: https://github.com/ecoinfAEET/Reproducibilidad/blob/master/Repro_ms.Rmd#tabla-1
