### ISSUE TITLE
Derechos de autor comics

### ISSUE THREAD

**Issue by ibartomeus** [ecoinfAEET/Reproducibilidad#6]
Habria que conseguirlos? 

Para la Figura 1, a mi no me parece una gran perdida si no la podemos poner.
Para la Figura 5 es fácil crear un directorio de archivos con esos nombres de archivos (o otros parecidos) y hacer una captura de pantalla. Sí os parece lo puedo hacer yo y nos ahorramos pedir permiso.

**Comment by ajpelu** [comment]
Estoy de acuerdo, Nacho. Adelante
